apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-logging-operator
  namespace: openshift-logging
spec:
  channel: stable-5.6
  installPlanApproval: Automatic
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace

